services:
  mongo:
    image: mongo:6.0
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
      # - ./db/backup.agz:/database_backup/backup.agz # eventually restore from backup

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  worker:
    build:
      context: .
      dockerfile: Dockerfile   # reuse the same image as the web app
    command: python worker.py
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
      - ./temp:/app/temp
      - ./result:/app/result

volumes:
  mongo_data:
